del "%OSGEO4W_STARTMENU%\QGIS Desktop 3.44.3.lnk"
del "%OSGEO4W_STARTMENU%\Qt Designer with QGIS 3.44.3 custom widgets.lnk"
rmdir "%OSGEO4W_STARTMENU%"
del "%OSGEO4W_DESKTOP%\QGIS Desktop 3.44.3.lnk"
del "%OSGEO4W_DESKTOP%\Qt Designer with QGIS 3.44.3 custom widgets.lnk"
rmdir "%OSGEO4W_DESKTOP%"
del "%OSGEO4W_ROOT%\bin\qgis.bat"
del "%OSGEO4W_ROOT%\bin\qgis-bin.vars"
del "%OSGEO4W_ROOT%\bin\qgis-bin.env"
del "%OSGEO4W_ROOT%\bin\qgis-designer.bat"
del "%OSGEO4W_ROOT%\apps\qgis\python\qgis\qgisconfig.py"
del "%OSGEO4W_ROOT%\apps\qgis\bin\qgis.reg"
del /s /q "%OSGEO4W_ROOT%\apps\qgis\python\*.pyc"
